apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: 8e27d218-9652-72b4-d927-2ba9bbe1803f
  AVP_SECRET_ID: 89e49dce-bcc2-35cd-ea17-e8c1f1f9bd75
  AVP_TYPE: vault
  VAULT_ADDR: http://10.245.34.165:8200/
